FROM electronuserland/builder:wine

ENV ELECTRON_CACHE="/root/.cache/electron"
ENV ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder"

WORKDIR /build_dir

COPY . .

RUN yarn

CMD [ "yarn", "build:docker" ]
